<a href="https://colab.research.google.com/github/fedeprocops/Data-analysis-portfolio/blob/main/notebooks/Sprint9_Time_Series_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sprint 9: Time Series Basics

In [1]:
import pandas as pd

In [2]:
from google.colab import files

uploaded = files.upload()

Saving netflix_titles_cleaned.csv to netflix_titles_cleaned.csv

In [5]:
df = pd.read_csv("netflix_titles_cleaned.csv")

In [6]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

In [8]:
df["date_added"].dtype

dtype('O')

Utilizziamo set_indext('date') per impostare la colonna date come indice visto che nelle serie temporali, il tempo diventa la dimensione principale dell'analisi. In questo modo è possibile eseguire operazioni specifiche sulle date, come selezioni per periodo, aggregazioni temporali e calcolo di medie mobili.

In [11]:
df['date_added'].head()

0    September 25, 2021
1    September 24, 2021
2    September 24, 2021
3    September 24, 2021
4    September 24, 2021
Name: date_added, dtype: object

Conversione del formato time: con pd.to_datetime

In [12]:
df['date_added'] = pd.to_datetime(
    df['date_added'],
    errors='coerce'
)

Estrazione dei componenti temporali

In [13]:
df['year_added'] = df['date_added'].dt.year

In [14]:
df['month_added'] = df['date_added'].dt.month

In [15]:
df['month_name'] = df['date_added'].dt.month_name()

In [16]:
df['weekday'] = df['date_added'].dt.day_name()

In [17]:
df['day'] = df['date_added'].dt.day

In [18]:
df[['date_added', 'year_added', 'month_name', 'weekday']].head()

  date_added  year_added month_name   weekday
0 2021-09-25      2021.0  September  Saturday
1 2021-09-24      2021.0  September    Friday
2 2021-09-24      2021.0  September    Friday
3 2021-09-24      2021.0  September    Friday
4 2021-09-24      2021.0  September    Friday

In [19]:
df['year_added'].value_counts().sort_index()

year_added
2008.0       2
2009.0       2
2010.0       1
2011.0      13
2012.0       3
2013.0      10
2014.0      23
2015.0      73
2016.0     415
2017.0    1161
2018.0    1624
2019.0    1999
2020.0    1878
2021.0    1498
Name: count, dtype: int64

Il numero di film aggiunti al catalogo Netflix cresce costantemente fino al 2019, anno in cui raggiunge il valore massimo. Successivamente si osserva una riduzione nel 2020 e nel 2021. Una possibile spiegazione potrebbe essere un cambiamento nella strategia di contenuti della piattaforma o fattori esterni che hanno influenzato la produzione e la distribuzione cinematografica. Per verificare l'ipotesi di una maggiore preferenza verso le serie TV sarebbero necessari dati sulle visualizzazioni o sulle abitudini degli utenti.

Convertiamo la colonna date_added e smontiamo i suoi componenti:

In [25]:
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,weekday,day
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021.0,9.0,September,Saturday,25.0
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021.0,9.0,September,Friday,24.0
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021.0,9.0,September,Friday,24.0
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021.0,9.0,September,Friday,24.0
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021.0,9.0,September,Friday,24.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8785,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",2019.0,11.0,November,Wednesday,20.0
8786,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",2019.0,7.0,July,Monday,1.0
8787,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,2019-11-01,2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,2019.0,11.0,November,Friday,1.0
8788,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",2020.0,1.0,January,Saturday,11.0
8789,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,2019.0,3.0,March,Saturday,2.0

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8790 entries, 0 to 8789
Data columns (total 17 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8790 non-null   object
 1   type          8790 non-null   object
 2   title         8790 non-null   object
 3   director      8790 non-null   object
 4   cast          8790 non-null   object
 5   country       8790 non-null   object
 6   date_added    8702 non-null   datetime64[ns]
 7   release_year  8790 non-null   int64
 8   rating        8790 non-null   object
 9   duration      8790 non-null   object
 10  listed_in     8790 non-null   object
 11  description   8790 non-null   object
 12  year_added    8702 non-null   float64
 13  month_added   8702 non-null   float64
 14  month_name    8702 non-null   object
 15  weekday       8702 non-null   object
 16  day           8702 non-null   float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(12)
memory usage: 1.1+ MB

In [28]:
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.month
df['month_name'] = df['date_added'].dt.month_name()
df['weekday'] = df['date_added'].dt.day_name()

In [29]:
df[
    ['date_added', 'year_added', 'month_added', 'month_name', 'weekday']
].head()

  date_added  year_added  month_added month_name   weekday
0 2021-09-25      2021.0          9.0  September  Saturday
1 2021-09-24      2021.0          9.0  September    Friday
2 2021-09-24      2021.0          9.0  September    Friday
3 2021-09-24      2021.0          9.0  September    Friday
4 2021-09-24      2021.0          9.0  September    Friday

In [30]:
df['year_added'].value_counts().sort_index()

year_added
2008.0       2
2009.0       2
2010.0       1
2011.0      13
2012.0       3
2013.0      10
2014.0      23
2015.0      73
2016.0     415
2017.0    1161
2018.0    1624
2019.0    1999
2020.0    1878
2021.0    1498
Name: count, dtype: int64

In [31]:
df_time = df.set_index('date_added')

In [32]:
df_time = df_time.sort_index()

In [33]:
df_time.loc['2019-09']

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,weekday,day
date_added,,,,,,,,,,,,,,,,
2019-09-01,s3542,TV Show,Naruto,Hayato Date,"Junko Takeuchi, Chie Nakamura, Noriaki Sugiyam...",Japan,2006,TV-14,9 Seasons,"Anime Series, International TV Shows","Guided by the spirit demon within him, orphane...",2019.0,9.0,September,Sunday,1.0
2019-09-01,s3543,Movie,Olmo & the Seagull,"Petra Costa, Lea Glob","Olivia Corsini, Sergio Nicolai, Arman Saribeky...","Denmark, Brazil, France, Portugal, Sweden",2014,TV-MA,82 min,"Dramas, Independent Movies, International Movies",A pregnancy forces an actress out of her lates...,2019.0,9.0,September,Sunday,1.0
2019-09-01,s3541,TV Show,Moving Art,Unknown,Unknown,United States,2018,TV-G,3 Seasons,"Docuseries, Science & Nature TV",Experience nature's art as filmmaker Louie Sch...,2019.0,9.0,September,Sunday,1.0
2019-09-01,s6760,Movie,First Kill,Steven C. Miller,"Hayden Christensen, Bruce Willis, Gethin Antho...","United Kingdom, Canada, United States",2017,R,102 min,Action & Adventure,A stock broker brings his young son back to th...,2019.0,9.0,September,Sunday,1.0
2019-09-01,s8242,Movie,The CEO,Kunle Afolayan,"Wale Ojo, Jimmy Jean-Louis, Hilda Dokubo, Nico...",Nigeria,2016,TV-14,109 min,"Dramas, International Movies, Thrillers",A group of executives heads to a telecommunica...,2019.0,9.0,September,Sunday,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2019-09-28,s6624,Movie,Domino,Brian De Palma,"Nikolaj Coster-Waldau, Carice van Houten, Eriq...","Denmark, France, Belgium, Italy, Netherlands, ...",2019,R,89 min,"International Movies, Thrillers",A Copenhagen police officer hunts for the man ...,2019.0,9.0,September,Saturday,28.0
2019-09-28,s3481,Movie,TUNA GIRL,Mana Yasuda,"Fuka Koshiba, Tom Fujita, Hidetoshi Hoshida, H...",Japan,2019,TV-PG,90 min,"Dramas, International Movies",A clumsy but cheerful fisheries student strugg...,2019.0,9.0,September,Saturday,28.0
2019-09-28,s3480,Movie,Cultivating the Seas: History and Future of th...,Mana Yasuda,Unknown,Unknown,2019,TV-PG,45 min,"Documentaries, International Movies",An in-depth look at the full-cycle breeding pr...,2019.0,9.0,September,Saturday,28.0
2019-09-30,s3478,TV Show,Gotham,Danny Cannon,"Ben McKenzie, Donal Logue, Jada Pinkett Smith,...",United States,2019,TV-MA,5 Seasons,"Crime TV Shows, TV Action & Adventure, TV Dramas","Long before he was commissioner, rookie cop Ja...",2019.0,9.0,September,Monday,30.0
2019-09-30,s3479,Movie,Mo Gilligan: Momentum,Chris Howe,Mo Gilligan,United Kingdom,2019,TV-MA,64 min,Stand-Up Comedy,Comedian Mo Gilligan blends smooth moves and s...,2019.0,9.0,September,Monday,30.0

Tutti i titoli di settembre 2019

In [35]:
df_time = df.set_index('date_added')
df_time = df_time.sort_index()

In [36]:
df_time.head()

,show_id,type,title,director,cast,country,release_year,rating,duration,listed_in,description,year_added,month_added,month_name,weekday,day
date_added,,,,,,,,,,,,,,,,
2008-01-01,s5958,Movie,To and From New York,Sorin Dan Mihalcescu,"Barbara King, Shaana Diya, John Krisiukenas, Y...",United States,2006,TV-MA,81 min,"Dramas, Independent Movies, Thrillers","While covering a story in New York City, a Sea...",2008.0,1.0,January,Tuesday,1.0
2008-02-04,s6612,TV Show,Dinner for Five,Unknown,Unknown,United States,2007,TV-MA,1 Season,Stand-Up Comedy & Talk Shows,"In each episode, four celebrities join host Jo...",2008.0,2.0,February,Monday,4.0
2009-05-05,s5957,Movie,Just Another Love Story,Ole Bornedal,"Anders W. Berthelsen, Rebecka Hemse, Nikolaj L...",Denmark,2007,TV-MA,104 min,"Dramas, International Movies",When he causes a car accident that leaves a yo...,2009.0,5.0,May,Tuesday,5.0
2009-11-18,s5956,Movie,Splatter,Joe Dante,"Corey Feldman, Tony Todd, Tara Leigh, Erin Way...",United States,2009,TV-MA,29 min,Horror Movies,"After committing suicide, a washed-up rocker r...",2009.0,11.0,November,Wednesday,18.0
2010-11-01,s7371,Movie,Mad Ron's Prevues from Hell,Jim Monaco,"Nick Pawlow, Jordu Schell, Jay Kushwara, Micha...",United States,1987,NR,84 min,"Cult Movies, Horror Movies","This collection cherry-picks trailers, forgott...",2010.0,11.0,November,Monday,1.0

In [37]:
df_time.index

DatetimeIndex(['2008-01-01', '2008-02-04', '2009-05-05', '2009-11-18',
               '2010-11-01', '2011-05-17', '2011-09-27', '2011-10-01',
               '2011-10-01', '2011-10-01',
               ...
                      'NaT',        'NaT',        'NaT',        'NaT',
                      'NaT',        'NaT',        'NaT',        'NaT',
                      'NaT',        'NaT'],
              dtype='datetime64[ns]', name='date_added', length=8790, freq=None)

In [38]:
titles_per_year = df_time.resample('YE').size()
titles_per_year

date_added
2008-12-31       2
2009-12-31       2
2010-12-31       1
2011-12-31      13
2012-12-31       3
2013-12-31      10
2014-12-31      23
2015-12-31      73
2016-12-31     415
2017-12-31    1161
2018-12-31    1624
2019-12-31    1999
2020-12-31    1878
2021-12-31    1498
dtype: int64

Con questi due step abbiamo raggruppato i dati per fine anno e contato quante righe ci sono in ogni periodo. Possiamo fare una lettura più pulita per anni e per mese

In [39]:
titles_per_year.index = titles_per_year.index.year
titles_per_year

date_added
2008       2
2009       2
2010       1
2011      13
2012       3
2013      10
2014      23
2015      73
2016     415
2017    1161
2018    1624
2019    1999
2020    1878
2021    1498
dtype: int64

In [40]:
titles_per_month = df_time.resample('ME').size()
titles_per_month.head()

date_added
2008-01-31    1
2008-02-29    1
2008-03-31    0
2008-04-30    0
2008-05-31    0
dtype: int64

In [41]:
df_time.resample('YE').size()

date_added
2008-12-31       2
2009-12-31       2
2010-12-31       1
2011-12-31      13
2012-12-31       3
2013-12-31      10
2014-12-31      23
2015-12-31      73
2016-12-31     415
2017-12-31    1161
2018-12-31    1624
2019-12-31    1999
2020-12-31    1878
2021-12-31    1498
dtype: int64

Questo comando raggruppa i dati per ogni fine anno (YE=YEar End) e conta quante righe ci sono per ciascuno.
Risponde alla domanda: quanti titoli sono stati aggiungi al catalogo ogni anno?

In [42]:
df_time.resample('ME').size()

date_added
2008-01-31      1
2008-02-29      1
2008-03-31      0
2008-04-30      0
2008-05-31      0
             ...
2021-05-31    132
2021-06-30    207
2021-07-31    257
2021-08-31    178
2021-09-30    183
Length: 165, dtype: int64

Quanti titoli sono stati aggiunti al catalogo in ciascun mese di ciascun anno?

*Rolling Windows and Moving Average*

In [43]:
titles_per_month = df_time.resample('ME').size()

In [44]:
titles_per_month.rolling(3).mean()

date_added
2008-01-31           NaN
2008-02-29           NaN
2008-03-31      0.666667
2008-04-30      0.333333
2008-05-31      0.000000
                 ...
2021-05-31    144.000000
2021-06-30    175.666667
2021-07-31    198.666667
2021-08-31    214.000000
2021-09-30    206.000000
Length: 165, dtype: float64

Per ogni mese, calcola la media degli ultimi 3 mesi disponibili.

In [45]:
titles_per_month.rolling(12).mean()

date_added
2008-01-31           NaN
2008-02-29           NaN
2008-03-31           NaN
2008-04-30           NaN
2008-05-31           NaN
                 ...
2021-05-31    146.833333
2021-06-30    151.083333
2021-07-31    160.333333
2021-08-31    164.416667
2021-09-30    165.666667
Length: 165, dtype: float64

Qual è il trend medio degli ultimi 12 mesi?