<a href="https://colab.research.google.com/github/fedeprocops/Data-analysis-portfolio/blob/main/notebooks/sprint_08_merging_joining_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sprint 8: Merging and Joining DataFrames

In [1]:
import pandas as pd

In [2]:
from google.colab import files
uploaded = files.upload()

Saving netflix_titles_cleaned.csv to netflix_titles_cleaned.csv

In [3]:
df = pd.read_csv('netflix_titles_cleaned.csv')

In [4]:
customers = pd.DataFrame({
    "customer_id": [1, 2, 3, 4],
    "name": ["Mario", "Luca", "Anna", "Sara"]
})

In [5]:
orders = pd.DataFrame({
    "order_id": [101, 102, 103],
    "customer_id": [1, 1, 3],
    "amount": [50, 20, 80]
})

In [6]:
inner_join = pd.merge(customers, orders, on="customer_id", how="inner")

left_join = pd.merge(customers, orders, on="customer_id", how="left")

outer_join = pd.merge(customers, orders, on="customer_id", how="outer")

In [7]:
inner_join = pd.merge(customers, orders, on="customer_id", how="inner")

In [8]:
inner_join

   customer_id   name  order_id  amount
0            1  Mario       101      50
1            1  Mario       102      20
2            3   Anna       103      80

In [9]:
left_join

   customer_id   name  order_id  amount
0            1  Mario     101.0    50.0
1            1  Mario     102.0    20.0
2            2   Luca       NaN     NaN
3            3   Anna     103.0    80.0
4            4   Sara       NaN     NaN

In [10]:
outer_join

   customer_id   name  order_id  amount
0            1  Mario     101.0    50.0
1            1  Mario     102.0    20.0
2            2   Luca       NaN     NaN
3            3   Anna     103.0    80.0
4            4   Sara       NaN     NaN

In [11]:
debug_merge = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="outer",
    indicator=True
)

debug_merge

   customer_id   name  order_id  amount     _merge
0            1  Mario     101.0    50.0       both
1            1  Mario     102.0    20.0       both
2            2   Luca       NaN     NaN  left_only
3            3   Anna     103.0    80.0       both
4            4   Sara       NaN     NaN  left_only

In [12]:
validated = pd.merge(
    customers,
    orders,
    on="customer_id",
    validate="one_to_many"
)

validated

   customer_id   name  order_id  amount
0            1  Mario       101      50
1            1  Mario       102      20
2            3   Anna       103      80

In [13]:
products = pd.DataFrame({
    "product_id": [1, 2, 3],
    "product_name": ["Laptop", "Mouse", "Keyboard"]
})


sales = pd.DataFrame({
    "sale_id": [1, 2, 3, 4],
    "product_id": [1, 1, 2, 4],
    "quantity": [2, 1, 5, 3]
})

In [14]:
products

   product_id product_name
0           1       Laptop
1           2        Mouse
2           3     Keyboard

In [15]:
sales

   sale_id  product_id  quantity
0        1           1         2
1        2           1         1
2        3           2         5
3        4           4         3

In [17]:
product_sales = pd.merge(
    products, sales,
    on="product_id",
    how="left",
    )

In [18]:
product_sales

   product_id product_name  sale_id  quantity
0           1       Laptop      1.0       2.0
1           1       Laptop      2.0       1.0
2           2        Mouse      3.0       5.0
3           3     Keyboard      NaN       NaN